name: hep
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pycurl
  - readchar
  - fsspec
  # numerical
  - numpy
  - scipy
  - pandas
  - pyarrow
  - numba
  - networkx
  # visualization
  - nodejs
  - matplotlib
  - bokeh
  - graphviz
  - pip:
      - graphviz
      - pyvis
  - rich
  # parallel
  - dask
  - dask-jobqueue
  - dask-awkward
  - dask-histogram
  # benchmarks
  - scalene
  # Scikit-HEP
  - coffea
  - uproot
  - awkward
  - awkward-pandas
  - hist
  - particle
  - correctionlib
