name: ml
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  # machine learning
  - pytorch::pytorch
  - pytorch::pytorch-cuda=12.1
  - scikit-learn
  # monitor
  - gevent
  - gevent-websocket
  - flask
  - flask-socketio
